# Iniciación a los tensores

Cada uno de los frameworks (Tensorflow y Pytorch) están basados en Tensores. Aunque existen muchas formas de entender un Tensor, una de ellas es pensar en un Numpy Array que puede ser calculado con la potencia de GPU (de ahí que la popularización del deep learning haya hecho incrementar el coste de las tarjetas gráficas y empresas como NVIDIA y AMD se hayan revalorizado tanto)

En este pequeño work-book vamos a realizar operaciones básicas con tensores


In [1]:
# Importamos las librerías
from __future__ import print_function
import torch

Una matriz 5x3 sin inicializar

In [2]:
x = torch.empty(5, 3)
print(x)


tensor([[5.8709e+33, 5.1147e-43, 6.6782e+36],
        [5.1147e-43, 1.2135e+34, 5.1147e-43],
        [3.9219e+28, 0.0000e+00, 3.9219e+28],
        [0.0000e+00, 5.7834e+33, 5.1147e-43],
        [5.8709e+33, 5.1147e-43, 6.6781e+36]])


Una matriz inicializada aleatoriamente

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0602, 0.4929, 0.0116],
        [0.4246, 0.9488, 0.5669],
        [0.0038, 0.1822, 0.1100],
        [0.9303, 0.3423, 0.3020],
        [0.8764, 0.3072, 0.3161]])


Varios ejemplos

In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Un tensor basado en otro tensor (adquiere sus propiedades)

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.5691,  0.5236,  1.2831],
        [ 0.5827,  0.0131,  0.2407],
        [ 0.8046, -1.0317, -0.3607],
        [ 0.3458,  0.1312, -1.1193],
        [ 0.1494,  0.0816,  0.4106]])
torch.Size([5, 3])


### Operaciones básicas con tensores
En general puedes realizar todas las operaciones como con los arrays Numpys. Para una detalla descripción de las mismas (+100 operaciones) consultar la documentación aquí https://pytorch.org/docs/stable/torch.html

Aquí vemos algunos ejemplos

In [7]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 3.4487,  1.2202,  1.4641],
        [ 1.5686,  0.4549,  1.1764],
        [ 1.5243, -0.8150,  0.1804],
        [ 0.6102,  0.5255, -0.9695],
        [ 0.6669,  0.4528,  0.8234]])


In [8]:
print(torch.add(x, y))

tensor([[ 3.4487,  1.2202,  1.4641],
        [ 1.5686,  0.4549,  1.1764],
        [ 1.5243, -0.8150,  0.1804],
        [ 0.6102,  0.5255, -0.9695],
        [ 0.6669,  0.4528,  0.8234]])


In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 3.4487,  1.2202,  1.4641],
        [ 1.5686,  0.4549,  1.1764],
        [ 1.5243, -0.8150,  0.1804],
        [ 0.6102,  0.5255, -0.9695],
        [ 0.6669,  0.4528,  0.8234]])


In [10]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 3.4487,  1.2202,  1.4641],
        [ 1.5686,  0.4549,  1.1764],
        [ 1.5243, -0.8150,  0.1804],
        [ 0.6102,  0.5255, -0.9695],
        [ 0.6669,  0.4528,  0.8234]])


In [11]:
# Numpy-like indexing
print(x[:, 1])

tensor([ 0.5236,  0.0131, -1.0317,  0.1312,  0.0816])


Realizar "resize" de los tensores. Muy util al trabajar en deep learning

In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


#### Un tensor se puede transformar a numpy y viceversa. También se puede mandar a cualquier dispositivo como por ejemplo CUDA

In [13]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [14]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [15]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Y al revés

In [20]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [24]:
# Esta celda solo correra si tenemos instalado pytorch con GPU

# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!